2011/07/07 23:42:20 [error] [php] Undefined index: model (E:\Projects\Code\PHP\gapp\protected\controllers\ApiController.php:28)
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(278): ApiController->runAction()
#1 E:\Projects\Code\PHP\yii\framework\web\CController.php(257): ApiController->runActionWithFilters()
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): ApiController->run()
#3 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController()
#4 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#5 E:\Projects\Code\PHP\gapp\index.php(13): CWebApplication->run()
REQUEST_URI=/gapp/index.php/api/list/places
in E:\Projects\Code\PHP\gapp\protected\controllers\ApiController.php (28)
in E:\Projects\Code\PHP\gapp\index.php (13)
2011/07/08 00:03:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "places".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('places')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('places')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/places/1/ge...')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/places/1/get
2011/07/08 00:23:24 [error] [php] strncasecmp() expects parameter 1 to be string, array given (E:\Projects\Code\PHP\yii\framework\web\CUrlManager.php:662)
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CUrlManager.php(225): CUrlManager->createUrlRule()
#1 E:\Projects\Code\PHP\yii\framework\web\CUrlManager.php(205): CUrlManager->processRules()
#2 E:\Projects\Code\PHP\yii\framework\base\CModule.php(372): CUrlManager->init()
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(501): CWebApplication->getComponent()
#4 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(135): CWebApplication->getUrlManager()
#5 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#6 E:\Projects\Code\PHP\gapp\index.php(13): CWebApplication->run()
REQUEST_URI=/gapp/index.php/api/category/1
in E:\Projects\Code\PHP\gapp\index.php (13)
2011/07/08 01:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "item".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('item')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('item')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/item/1')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/item/1
2011/07/08 01:12:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "item".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('item')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('item')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/item/1')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/item/1
2011/07/08 01:13:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "category".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('category')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('category')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/category/1')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/category/1
2011/07/08 01:14:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "category".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('category')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('category')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/category/1')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/category/1
2011/07/08 01:14:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "category".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('category')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('category')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/category/1')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/category/1
2011/07/08 01:14:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "category".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('category')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('category')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/category/1')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/category/1
2011/07/08 01:15:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "category".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('category')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('category')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/category/1')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/category/1
2011/07/08 01:16:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "category".' in E:\Projects\Code\PHP\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\web\CController.php(262): CController->missingAction('category')
#1 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('category')
#2 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/category/1')
#3 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp/index.php/api/category/1/
2011/07/08 01:17:03 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'where clause'. The SQL statement executed was: SELECT * FROM `items` `t` WHERE parent_id=:parent_id LIMIT 1.
in E:\Projects\Code\PHP\gapp\protected\controllers\ApiController.php (66)
in E:\Projects\Code\PHP\gapp\index.php (13)
2011/07/08 01:17:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'where clause'. The SQL statement executed was: SELECT * FROM `items` `t` WHERE parent_id=:parent_id LIMIT 1' in E:\Projects\Code\PHP\yii\framework\db\CDbCommand.php:516
Stack trace:
#0 E:\Projects\Code\PHP\yii\framework\db\CDbCommand.php(393): CDbCommand->queryInternal('fetch', Array, Array)
#1 E:\Projects\Code\PHP\yii\framework\db\ar\CActiveRecord.php(1290): CDbCommand->queryRow()
#2 E:\Projects\Code\PHP\yii\framework\db\ar\CActiveRecord.php(1396): CActiveRecord->query(Object(CDbCriteria))
#3 E:\Projects\Code\PHP\gapp\protected\controllers\ApiController.php(66): CActiveRecord->find('parent_id=:pare...', Array)
#4 E:\Projects\Code\PHP\yii\framework\web\actions\CInlineAction.php(50): ApiController->actionView()
#5 E:\Projects\Code\PHP\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#6 E:\Projects\Code\PHP\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#7 E:\Projects\Code\PHP\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(277): CController->run('view')
#9 E:\Projects\Code\PHP\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/view')
#10 E:\Projects\Code\PHP\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 E:\Projects\Code\PHP\gapp\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/gapp/index.php/api/category/1/items
2011/07/15 12:38:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'bee20320_tc'@'localhost' (using password: YES)' in D:\Job\Geo\source\yii\framework\db\CDbConnection.php:364
Stack trace:
#0 D:\Job\Geo\source\yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 D:\Job\Geo\source\yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 D:\Job\Geo\source\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\Job\Geo\source\yii\framework\base\CApplication.php(429): CModule->getComponent('db')
#4 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(609): CApplication->getDb()
#5 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(2275): CActiveRecord->getDbConnection()
#6 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Item))
#7 D:\Job\Geo\source\gapp_service\gapp\protected\models\Item.php(24): CActiveRecord::model('Item')
#8 D:\Job\Geo\source\gapp_service\gapp\protected\controllers\ApiController.php(31): Item::model()
#9 D:\Job\Geo\source\yii\framework\web\actions\CInlineAction.php(50): ApiController->actionList()
#10 D:\Job\Geo\source\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 D:\Job\Geo\source\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#12 D:\Job\Geo\source\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\Job\Geo\source\yii\framework\web\CWebApplication.php(277): CController->run('list')
#14 D:\Job\Geo\source\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/list')
#15 D:\Job\Geo\source\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#16 D:\Job\Geo\source\gapp_service\gapp\index.php(13): CApplication->run()
#17 {main} REQUEST_URI=/gapp_service/gapp/index.php/api/item
2011/07/15 12:41:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'bee20320_tc'@'localhost' (using password: YES)' in D:\Job\Geo\source\yii\framework\db\CDbConnection.php:364
Stack trace:
#0 D:\Job\Geo\source\yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 D:\Job\Geo\source\yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 D:\Job\Geo\source\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\Job\Geo\source\yii\framework\base\CApplication.php(429): CModule->getComponent('db')
#4 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(609): CApplication->getDb()
#5 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(2275): CActiveRecord->getDbConnection()
#6 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Item))
#7 D:\Job\Geo\source\gapp_service\gapp\protected\models\Item.php(24): CActiveRecord::model('Item')
#8 D:\Job\Geo\source\gapp_service\gapp\protected\controllers\ApiController.php(31): Item::model()
#9 D:\Job\Geo\source\yii\framework\web\actions\CInlineAction.php(50): ApiController->actionList()
#10 D:\Job\Geo\source\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 D:\Job\Geo\source\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#12 D:\Job\Geo\source\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\Job\Geo\source\yii\framework\web\CWebApplication.php(277): CController->run('list')
#14 D:\Job\Geo\source\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/list')
#15 D:\Job\Geo\source\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#16 D:\Job\Geo\source\gapp_service\gapp\index.php(13): CApplication->run()
#17 {main} REQUEST_URI=/gapp_service/gapp/index.php/api/item
2011/07/15 12:41:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'bee20320_tc'@'localhost' (using password: YES)' in D:\Job\Geo\source\yii\framework\db\CDbConnection.php:364
Stack trace:
#0 D:\Job\Geo\source\yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 D:\Job\Geo\source\yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 D:\Job\Geo\source\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 D:\Job\Geo\source\yii\framework\base\CApplication.php(429): CModule->getComponent('db')
#4 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(609): CApplication->getDb()
#5 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(2275): CActiveRecord->getDbConnection()
#6 D:\Job\Geo\source\yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Item))
#7 D:\Job\Geo\source\gapp_service\gapp\protected\models\Item.php(24): CActiveRecord::model('Item')
#8 D:\Job\Geo\source\gapp_service\gapp\protected\controllers\ApiController.php(31): Item::model()
#9 D:\Job\Geo\source\yii\framework\web\actions\CInlineAction.php(50): ApiController->actionList()
#10 D:\Job\Geo\source\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 D:\Job\Geo\source\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#12 D:\Job\Geo\source\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\Job\Geo\source\yii\framework\web\CWebApplication.php(277): CController->run('list')
#14 D:\Job\Geo\source\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/list')
#15 D:\Job\Geo\source\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#16 D:\Job\Geo\source\gapp_service\gapp\index.php(13): CApplication->run()
#17 {main} REQUEST_URI=/gapp_service/gapp/index.php/api/item
2011/07/16 16:42:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "item.html".' in E:\Job\Geo\source\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Job\Geo\source\yii\framework\web\CController.php(262): CController->missingAction('item.html')
#1 E:\Job\Geo\source\yii\framework\web\CWebApplication.php(277): CController->run('item.html')
#2 E:\Job\Geo\source\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/item.html')
#3 E:\Job\Geo\source\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Job\Geo\source\gapp_service\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp_service/gapp/index.php/api/item.html
2011/07/16 16:47:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "item.html".' in E:\Job\Geo\source\yii\framework\web\CController.php:477
Stack trace:
#0 E:\Job\Geo\source\yii\framework\web\CController.php(262): CController->missingAction('item.html')
#1 E:\Job\Geo\source\yii\framework\web\CWebApplication.php(277): CController->run('item.html')
#2 E:\Job\Geo\source\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('api/item.html')
#3 E:\Job\Geo\source\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 E:\Job\Geo\source\gapp_service\gapp\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/gapp_service/gapp/index.php/api/item.html
